### ISSUE TITLE
About the original gui of ORB-SLAM 

### ISSUE THREAD

**Issue by Tianci-Wen** [HuajianUP/Photo-SLAM#10]
Hi, thanks for your excellent work!
I am trying to use your visualization tool to visualize 3D gaussians, and also want to use pangolin, the original visualization tool of ORB-SLAM3, to better observe the output of SLAM. 
I found that you almost completely commented out the visualization parts of pangolin and ORBSLAM3 in your code. 
I also tried it and found that **pangolin seems to be incompatible with cuda**. ​​In addition, **pangolin is also incompatible with the current opencv4.7**. 
I wonder if you have encountered similar problems, or can you share some reasons why you don't use the original visualization tool of ORB-SLAM3 pangolin?

**Comment by mirpouya** [comment]
> We used to apply pangolin-0.6 at an early stage of development, but finally switched to ImGUI for its more powerful customization. We also did this for ImGUI is more portable and thus can be integrated into our project, while pangolin requires users to install extra library. We have implemented main part of the original viewer features (i.e. drawing MapPoints and Keyframe frustums) and considered the original viewer unnecessay.

I cannot display the restul in my docker:

(base) pouya@mir:~$ echo $DISPLAY
:1
(base) pouya@mir:~$ xhost +local:docker
non-network local connections being added to access control list
(base) pouya@mir:~$ sudo docker run -it --gpus all \
    -e DISPLAY=$DISPLAY \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    photo-slam:work-in-progress
[sudo] password for pouya: 

==========
== CUDA ==
==========

CUDA Version 11.8.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

root@85bfd960eeec:/Photo-SLAM# ls
CMakeLists.txt  README.md  cfg              include  src
LICENSE         bin        cuda_rasterizer  lib      third_party
LICENSE.md      build      data             results  viewer
ORB-SLAM3       build.sh   examples         scripts
root@85bfd960eeec:/Photo-SLAM# ./bin/replica_rgbd \
    ./ORB-SLAM3/Vocabulary/ORBvoc.txt \
    ./cfg/ORB_SLAM3/RGB-D/Replica/office0.yaml \
    ./cfg/gaussian_mapper/RGB-D/Replica/replica_rgbd.yaml \
    /Photo-SLAM/data/Replica/office0 \
    /Photo-SLAM/results
CUDA available! Training on GPU.

ORB-SLAM3 Copyright (C) 2017-2020 Carlos Campos, Richard Elvira, Juan J. Gómez, José M.M. Montiel and Juan D. Tardós, University of Zaragoza.
ORB-SLAM2 Copyright (C) 2014-2016 Raúl Mur-Artal, José M.M. Montiel and Juan D. Tardós, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: RGB-D
Loading settings from ./cfg/ORB_SLAM3/RGB-D/Replica/office0.yaml
	-Loaded camera 1
Camera.newHeight optional parameter does not exist...
Camera.newWidth optional parameter does not exist...
	-Loaded image info
	-Loaded RGB-D calibration
	-Loaded ORB settings
Viewer.imageViewScale optional parameter does not exist...
	-Loaded viewer settings
System.LoadAtlasFromFile optional parameter does not exist...
System.SaveAtlasToFile optional parameter does not exist...
	-Loaded Atlas settings
System.thFarPoints optional parameter does not exist...
	-Loaded misc parameters
----------------------------------
SLAM settings: 
	-Camera 1 parameters (Pinhole): [ 600 600 599.5 339.5 ]
	-Camera 1 distortion parameters: [  0.000238406 -0.000314798 -7.39231e-05 -2.7716e-05 0 ]
	-Original image size: [ 1200 , 680 ]
	-Current image size: [ 1200 , 680 ]
	-Sequence FPS: 30
	-RGB-D depth map factor: 6553.5
	-Features per image: 1600
	-ORB scale factor: 1.2
	-ORB number of scales: 8
	-Initial FAST threshold: 20
	-Min FAST threshold: 7


Loading ORB Vocabulary. This could take a while...
Vocabulary loaded!

Initialization of Atlas from scratch 
Creation of new map with id: 0
Creation of new map with last KF id: 0
Seq. Name: 
There are 1 cameras in the atlas
Camera 0 is pinhole
[Gaussian Mapper]CUDA available! Training on GPU.
[Gaussian Mapper]Reading parameters from "./cfg/gaussian_mapper/RGB-D/Replica/replica_rgbd.yaml"
[ImGuiViewer]Reading parameters from "./cfg/gaussian_mapper/RGB-D/Replica/replica_rgbd.yaml"

-------
Start processing sequence ...
Images in the sequence: 2000

First KF:0; Map init KF:0
New Map created with 1560 points
Segmentation fault (core dumped)
root@85bfd960eeec:/Photo-SLAM# echo $DISPLAY
:1
root@85bfd960eeec:/Photo-SLAM# 

can you please help me
