### ISSUE TITLE
> Hi Jiyu,

### ISSUE THREAD

**Issue by xiangw369** [HuajianUP/Photo-SLAM#13]
> Hi Jiyu,
> 
> We notice that the system is not compatible with the latest Pytorch. Please use the tested version.
> 
> ```
> wget https://download.pytorch.org/libtorch/cu118/libtorch-cxx11-abi-shared-with-deps-2.0.1%2Bcu118.zip -O libtorch-cu118.zip
> unzip libtorch-cu118.zip && rm libtorch-cu118.zip
> 
> # in CMakeLists.txt
> set(Torch_DIR ./libtorch/share/cmake/Torch)
> ```

Thank you so much about your kind reply! 
I've noticed this issue and I compile your code successfully in docker with the dockerfile provided by https://github.com/HuajianUP/Photo-SLAM/issues/2#issuecomment-2089933703.
However, when I try to run it, it seems another error occurred. So confusing it is that seems nobody have met this before. Could you please check for it and provide some suggestion?
Thanks a lot!
![2024-06-11 12-52-19 的屏幕截图](https://github.com/HuajianUP/Photo-SLAM/assets/172094211/82ee2ecf-a2cd-4136-9358-b7d3da6cf407)

_Originally posted by @Jiyu-Yao in https://github.com/HuajianUP/Photo-SLAM/issues/12#issuecomment-2160430352_

**Comment by kunyuwan** [comment]
Please tell me how to solve it, I also encountered the same problem

**Comment by Jiyu-Yao** [comment]
> Please tell me how to solve it, I also encountered the same problem

Have you solved it? I'm still confused about it. Thanks a lot!

**Comment by leihanchen** [comment]
@xiangw369 @Jiyu-Yao  Any updates on it, encountered the same issue with the build with the same dockerfile.
