### ISSUE TITLE
Replacement of slam methods

### ISSUE THREAD

**Issue by huzhanxiaoxue** [HuajianUP/Photo-SLAM#26]
Replacement of positional methods
1. Replace orbslam  with dataset truth values
2. vins replace orbslam
Currently looking at the code is not clear feasibility, can you help me analyze it?
翻译如下：
替换定位方法
1、用数据集真值替代slam位姿
2、vins替换orbslam
目前看代码还不清楚可行性，可以帮我分析一下吗

**Comment by liquorleaf** [comment]
您需要给Gaussian Mapper模块持续提供两个输入：
1.来自SLAM重建得到的有色点云，用于提供3DGS稠密化的种子；
2.关键帧（包括图片、位姿两个要素），用于创建GaussianKeyframe并添加到GaussianScene。
具体而言，需要修改gaussian_mapper.cpp关于获取并格式化SLAM数据的部分，并调用相应函数进行添加。

**Comment by respect-jz** [comment]
@huzhanxiaoxue 
佬，你好、我也跟你一样有相关的想法，可以加您个联系方式吗

**Comment by huzhanxiaoxue** [comment]
后面没做了，可以留你的联系方式我加你
@respect-jz

**Comment by respect-jz** [comment]
@huzhanxiaoxue 好的，zhoujie001218@gamil.com这是我的邮箱
