### ISSUE TITLE
Support for ROS

### ISSUE THREAD

**Issue by berniel** [HuajianUP/Photo-SLAM#27]
Hi Huajian!

Great thanks for such an excellent work! I wonder is there any plan to support ros for further application?

**Comment by liquorleaf** [comment]
The [original ORB-SLAM3 ROS support](https://github.com/UZ-SLAMLab/ORB_SLAM3/tree/master/Examples_old/ROS/ORB_SLAM3) might help.

**Comment by berniel** [comment]
Thanks for your kind reply! I've finished a ROS version for PhotoSLAM with the original ORB-SLAM3 ROS support. It just fits perfectly.

**Comment by caoyuhong001** [comment]
Hi @berniel, could you share your ROS vesrion PhotoSLAM if possible? Thanks in advance.
